/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDadosRouteImport } from './routes/app.dados'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppLancarRouteImport } from './routes/app.lancar'
import { Route as AppMovimentacoesRouteImport } from './routes/app.movimentacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDadosRoute = AppDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppLancarRoute = AppLancarRouteImport.update({
  id: '/lancar',
  path: '/lancar',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dados': typeof AppDadosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dados': typeof AppDadosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dados': typeof AppDadosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/lancar': typeof AppLancarRoute
  '/app/movimentacoes': typeof AppMovimentacoesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dados'
    | '/app/estoque'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dados'
    | '/app/estoque'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dados'
    | '/app/estoque'
    | '/app/lancar'
    | '/app/movimentacoes'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dados': {
      id: '/app/dados'
      path: '/dados'
      fullPath: '/app/dados'
      preLoaderRoute: typeof AppDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lancar': {
      id: '/app/lancar'
      path: '/lancar'
      fullPath: '/app/lancar'
      preLoaderRoute: typeof AppLancarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movimentacoes': {
      id: '/app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/app/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDadosRoute: typeof AppDadosRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppLancarRoute: typeof AppLancarRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDadosRoute: AppDadosRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppLancarRoute: AppLancarRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
